#!/usr/bin/env python3
"""Automated functional QA for the Hidden Homestay demo site (file:// demo mode)."""
import datetime
import json
import pathlib
import sys

from playwright.sync_api import sync_playwright

ROOT = pathlib.Path(__file__).resolve().parent.parent
URL = (ROOT / 'index.html').resolve().as_uri()
SHOTS = pathlib.Path('/home/user/qa-shots')
SHOTS.mkdir(exist_ok=True)

passed, failed = [], []


def check(name, cond, extra=''):
    (passed if cond else failed).append(name + (f'  [{extra}]' if extra and not cond else ''))
    print(('  PASS  ' if cond else '  FAIL  ') + name + (f'   -> {extra}' if extra else ''))


def run():
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page(viewport={'width': 1440, 'height': 960})
        errors = []
        page.on('console', lambda m: errors.append(m.text) if m.type == 'error' else None)
        page.on('pageerror', lambda e: errors.append(str(e)))

        print('== LOAD ==')
        page.goto(URL, wait_until='load')
        page.wait_for_timeout(1200)
        check('no console/page errors on load', not errors, '; '.join(errors[:3]))
        check('title', 'Hidden Homestay' in page.title(), page.title())
        check('hero headline present', page.locator('h1').inner_text().strip().startswith('Stay Somewhere'))
        check('3 room cards rendered', page.locator('.room-card').count() == 3)
        check('2 branch cards rendered', page.locator('.branch-card').count() == 2)
        page.screenshot(path=str(SHOTS / '01-home-desktop.png'))

        print('== SLIDER ==')
        idx = page.evaluate("Array.from(document.querySelectorAll('#showcaseFrame .slide')).findIndex(s=>s.classList.contains('active'))")
        page.wait_for_timeout(3400)
        idx2 = page.evaluate("Array.from(document.querySelectorAll('#showcaseFrame .slide')).findIndex(s=>s.classList.contains('active'))")
        check('slider advances after ~3s', idx != idx2, f'{idx} -> {idx2}')
        chip = page.locator('#chipName').inner_text()
        check('chip shows a room name', chip in ('Burger Room', 'Vintage Room', 'Fishing Room'), chip)
        ambient = page.evaluate("Array.from(document.querySelectorAll('#heroAmbient .amb')).filter(a=>a.classList.contains('active')).length")
        check('ambient layer syncs (exactly 1 active)', ambient == 1)

        print('== BOOKING STEP 1 ==')
        page.locator('.room-card').first.locator('button[data-book]').click()
        page.wait_for_timeout(400)
        check('overlay opens', page.locator('#bookingOverlay').evaluate("el=>el.classList.contains('open')"))
        check('pane 1 active', page.locator('.pane[data-pane="1"]').evaluate("el=>el.classList.contains('active')"))
        check('continue disabled before branch pick', page.locator('#actNext').is_disabled())
        page.screenshot(path=str(SHOTS / '02-step1-branch.png'))
        page.locator('#pickBranches .pick-card').nth(1).click()
        page.wait_for_timeout(200)
        check('branch card gets selected style', page.locator('#pickBranches .pick-card').nth(1).evaluate("el=>el.classList.contains('selected')"))
        check('continue enabled after pick', not page.locator('#actNext').is_disabled())
        page.locator('#actNext').click()
        page.wait_for_timeout(400)

        print('== BOOKING STEP 2 ==')
        check('pane 2 active', page.locator('.pane[data-pane="2"]').evaluate("el=>el.classList.contains('active')"))
        pre = page.evaluate("(id)=>document.querySelector(`#pickRooms .pick-card[data-room-id='${id}']`)?.classList.contains('selected')", 'burger')
        check('burger room preselected from homepage CTA', pre)
        page.screenshot(path=str(SHOTS / '03-step2-room.png'))
        page.locator('#pickRooms .pick-card[data-room-id="vintage"]').click()
        page.locator('#actNext').click()
        page.wait_for_timeout(400)

        print('== BOOKING STEP 3 (check-in/out, whole hours) ==')
        check('pane 3 active', page.locator('.pane[data-pane="3"]').evaluate("el=>el.classList.contains('active')"))
        check('review disabled before schedule', page.locator('#actNext').is_disabled())
        check('mode badge shows Demo', page.locator('#modeBadge').inner_text().lower() == 'demo', repr(page.locator('#modeBadge').inner_text()))
        check('6 hour chips', page.locator('#hourChips button').count() == 6)
        tomorrow = (datetime.date.today() + datetime.timedelta(days=1)).isoformat()
        page.fill('#bkDate', tomorrow)
        page.select_option('#bkIn', '14:00')
        # chip without checkout → fills it
        page.locator('#hourChips button[data-hours="2"]').click()
        page.wait_for_timeout(200)
        check('chip 2h auto-fills check-out 16:00', page.locator('#bkOut').input_value() == '16:00', page.locator('#bkOut').input_value())
        check('chip 2h highlighted', page.locator('#hourChips button[data-hours="2"]').evaluate("el=>el.classList.contains('active')"))
        # fractional duration rejected
        opts = page.eval_on_selector_all('#bkOut option', 'els => els.map(e => e.value).filter(v => v)')
        check('time pickers are whole-hours only (no minutes)', all(v.endswith(':00') for v in opts) and '15:30' not in opts, opts[:5])
        # checkout before checkin
        page.select_option('#bkOut', '13:00')
        page.wait_for_timeout(250)
        check('checkout-before-checkin flagged', page.locator('#schedChecks li[data-check="order"]').evaluate("el=>el.classList.contains('bad')"))
        # valid 3h
        page.select_option('#bkOut', '17:00')
        page.wait_for_timeout(300)
        dur = page.locator('#sumDur').inner_text()
        tot = page.locator('#sumTotal').inner_text()
        check('duration = 3 hrs', dur == '3 hrs', dur)
        check('total = $21.00 (7.00 x 3)', tot == '$21.00', tot)
        check('status shows demo availability', 'Available' in page.locator('#availStatus').inner_text() and 'Demo' in page.locator('#availStatus').inner_text())
        check('review enabled once valid', not page.locator('#actNext').is_disabled())
        page.screenshot(path=str(SHOTS / '04-step3-schedule.png'))
        page.locator('#actNext').click()
        page.wait_for_timeout(400)

        print('== BOOKING STEP 4 (review + KHQR) ==')
        check('pane 4 active', page.locator('.pane[data-pane="4"]').evaluate("el=>el.classList.contains('active')"))
        receipt = page.locator('#reviewReceipt').inner_text()
        check('receipt shows branch', 'Peng Hout' in receipt)
        check('receipt says Check-in / Check-out', 'Check-in' in receipt and 'Check-out' in receipt and 'Start time' not in receipt)
        check('receipt shows times', '2:00 PM' in receipt and '5:00 PM' in receipt)
        check('receipt shows total', '$21.00' in receipt)
        check('receipt has booking ref', 'HH-' in receipt)
        check('confirm disabled before details', page.locator('#actConfirm').is_disabled())
        check('KHQR hidden before agreeing', not page.locator('#paySection').evaluate("el=>el.classList.contains('open')"))
        page.screenshot(path=str(SHOTS / '05-step4-review.png'))
        page.fill('#bkName', 'Sokha Pen')
        page.fill('#bkPhone', '+855 12 345 678')
        page.locator('.agree').click()
        page.wait_for_timeout(700)
        check('KHQR section opens after agree', page.locator('#paySection').evaluate("el=>el.classList.contains('open')"))
        check('KHQR amount = $21.00', page.locator('#payAmount').inner_text() == '$21.00', page.locator('#payAmount').inner_text())
        canvas_drawn = page.evaluate("()=>{const c=document.querySelector('#khqrCanvas');const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let dark=0;for(let i=3;i<d.length;i+=4) if(d[i]>0 && (d[i-3]<100)) dark++; return dark;}")
        check('KHQR canvas actually drawn (dark modules)', canvas_drawn > 500, canvas_drawn)
        check('Pay Now button visible', page.locator('#abaPayBtn').is_visible())
        pay_href = page.locator('#abaPayBtn').get_attribute('href') or ''
        check('Pay Now = Bakong deeplink with exact amount', pay_href.startswith('https://bakong-deeplink.nbc.gov.kh/bakong/payment?qr=000201') and '540521.00' in pay_href, pay_href[:70])
        check('Pay Now button shows amount', page.locator('#abaPayAmt').inner_text() == '$21.00', page.locator('#abaPayAmt').inner_text())
        qr_bg = page.locator('.pay-qr').evaluate("el=>getComputedStyle(el).backgroundColor")
        check('payment card styled (white QR panel)', qr_bg == 'rgb(255, 255, 255)', qr_bg)
        check('confirm enabled after agree + details', not page.locator('#actConfirm').is_disabled())
        page.screenshot(path=str(SHOTS / '06-step4-khqr.png'), full_page=False)
        page.locator('#actConfirm').click()
        page.wait_for_timeout(600)

        print('== SUCCESS ==')
        check('pane 5 (success) active', page.locator('.pane[data-pane="5"]').evaluate("el=>el.classList.contains('active')"))
        success_txt = page.locator('.pane-success').inner_text()
        check('thanks message', 'Thank you for choosing' in success_txt)
        check('details repeated on success slip', 'Vintage Room' in success_txt and '$21.00' in success_txt and 'Sokha Pen' in success_txt)
        stored = page.evaluate("JSON.parse(localStorage.getItem('hiddenHomestayBookings')||'[]')")
        check('booking saved to localStorage', len(stored) == 1 and stored[0]['room'] == 'Vintage Room' and stored[0]['total'] == '$21.00', json.dumps(stored)[:120])
        page.screenshot(path=str(SHOTS / '07-success.png'))

        print('== MY BOOKINGS ==')
        page.locator('.pane-success [data-open-bookings]').click()
        page.wait_for_timeout(300)
        check('modal opens', page.locator('#bookingsModal').evaluate("el=>el.classList.contains('open')"))
        check('booking listed with ref', 'HH-' in page.locator('#bookingsBody').inner_text())
        page.screenshot(path=str(SHOTS / '08-mybookings.png'))
        page.locator('.bk-del').click()
        page.wait_for_timeout(300)
        stored2 = page.evaluate("JSON.parse(localStorage.getItem('hiddenHomestayBookings')||'[]')")
        check('remove deletes booking', len(stored2) == 0)
        page.locator('[data-close-bookings]').click()

        print('== RESET / RESUME ==')
        page.keyboard.press('Escape')
        page.wait_for_timeout(300)
        check('ESC closes overlay', not page.locator('#bookingOverlay').evaluate("el=>el.classList.contains('open')"))
        page.locator('#navLinks [data-book]').click()
        page.wait_for_timeout(400)
        check('after success, Book Now starts fresh at step 1', page.locator('.pane[data-pane="1"]').evaluate("el=>el.classList.contains('active')"))
        page.locator('#pickBranches .pick-card').first.click()
        page.locator('#actNext').click()
        page.wait_for_timeout(300)
        page.locator('#pickRooms .pick-card[data-room-id="burger"]').click()
        page.locator('#actNext').click()
        page.wait_for_timeout(300)
        page.locator('#overlayClose').click()
        page.wait_for_timeout(200)
        page.locator('#navLinks [data-book]').click()
        page.wait_for_timeout(400)
        check('reopening resumes flow at schedule', page.locator('.pane[data-pane="3"]').evaluate("el=>el.classList.contains('active')"))
        page.locator('#overlayClose').click()
        page.wait_for_timeout(200)

        print('== MOBILE (390x844) ==')
        mp = browser.new_page(viewport={'width': 390, 'height': 844}, is_mobile=True, has_touch=True)
        merrors = []
        mp.on('console', lambda m: merrors.append(m.text) if m.type == 'error' else None)
        mp.on('pageerror', lambda e: merrors.append(str(e)))
        mp.goto(URL, wait_until='load')
        mp.wait_for_timeout(1000)
        check('mobile: no console errors', not merrors, '; '.join(merrors[:3]))
        check('mobile: no horizontal overflow', mp.evaluate('document.documentElement.scrollWidth <= window.innerWidth + 1'))
        check('mobile: burger visible', mp.locator('#burger').is_visible())
        mp.screenshot(path=str(SHOTS / '09-home-mobile.png'))
        mp.locator('#burger').click()
        mp.wait_for_timeout(250)
        mp.screenshot(path=str(SHOTS / '10-mobile-menu.png'))
        mp.locator('.room-card').nth(2).locator('button[data-book]').click()
        mp.wait_for_timeout(500)
        check('mobile: booking overlay opens', mp.locator('#bookingOverlay').evaluate("el=>el.classList.contains('open')"))
        check('mobile: no overlay overflow', mp.evaluate('document.documentElement.scrollWidth <= window.innerWidth + 1'))
        mp.locator('#pickBranches .pick-card').first.click()
        mp.locator('#actNext').click()
        mp.wait_for_timeout(300)
        mp.locator('#pickRooms .pick-card[data-room-id="fishing"]').click()
        mp.locator('#actNext').click()
        mp.wait_for_timeout(300)
        mp.fill('#bkDate', tomorrow)
        mp.select_option('#bkIn', '20:00')
        mp.locator('#hourChips button[data-hours="2"]').click()
        mp.wait_for_timeout(300)
        check('mobile: fishing 2h total = $15.00', mp.locator('#sumTotal').inner_text() == '$15.00', mp.locator('#sumTotal').inner_text())
        mp.screenshot(path=str(SHOTS / '11-mobile-schedule.png'))
        mp.locator('#actNext').click()
        mp.wait_for_timeout(400)
        mp.fill('#bkName', 'Dara Chhan')
        mp.fill('#bkPhone', '012 999 888')
        mp.locator('.agree').click()
        mp.wait_for_timeout(600)
        check('mobile: KHQR visible after agree', mp.locator('#paySection').evaluate("el=>el.classList.contains('open')"))
        mp.locator('#actConfirm').click()
        mp.wait_for_timeout(500)
        check('mobile: success reached', mp.locator('.pane[data-pane="5"]').evaluate("el=>el.classList.contains('active')"))
        check('mobile: no overlay overflow at success', mp.evaluate('document.documentElement.scrollWidth <= window.innerWidth + 1'))
        mp.screenshot(path=str(SHOTS / '12-mobile-success.png'))
        browser.close()

    print('\n===========================')
    print(f'RESULT: {len(passed)} passed, {len(failed)} failed')
    if failed:
        print('FAILED:')
        for f in failed:
            print('  - ' + f)
        sys.exit(1)


if __name__ == '__main__':
    run()
